### ISSUE TITLE
Port NumFocus fiscal sponsorship post to weblog

### ISSUE THREAD

**Issue by jezdez** [conda/communications#15]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

I think we should port https://conda.discourse.group/t/conda-is-now-fiscally-sponsored-by-numfocus/150 to the weblog, for posterity sake.

**Comment by jezdez** [comment]
https://hackmd.io/@conda-dot-org/BkFWqVIOo might be a good start?

**Comment by tnabtaf** [comment]
This [has been posted to the blog](https://conda.org/blog/2022-12-14-fiscal-sponsorship).
