### ISSUE TITLE
Cleanup of workspace directory. Is this even an issue?

### ISSUE THREAD

**Issue by tnabtaf** [conda/communications#3]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

## Background

As [discussed in the Conda Communications Matrix Room](https://matrix.to/#/!zEKyVXqvfLUOBRmrqu:matrix.org/$o_b9THK8as_ahhIY3_R9aX6yCmk4t5W1pL9S5hGhBxE?via=matrix.org) we decided to use this GitHub repo as a collaborative workspace for drafting posts that will be placed elsewhere, such as on the community website, or the community forum.

Pull request #2 establishes the `/workspace` directory for this purpose.  That PR also includes a README with suggestions on how to work in that directory.  That guidance is minimal.

## But we don't want search engines to search the `/workspace` directory

We don't want searches pointing people to our directory.  We want them to point people to where the post was published.

How do we accomplish this?  Is this even a problem?

Some ideas:

* Delete pages once they are posted.  
  * However, there is value in having a directory of posts we have already created.  When we need to create something similar, we can just start with an easy to find copy of what we already did.
* Replace the draft page with a link to the URL where it was published.
  * This would work, and if we keep pages around then it would be good to track where they ended up anyway.  People would also be able to find the source through GitHub's history.
* Use GitHub to tell search engines not to go there!
  * This is the cleanest option, I just can't figure out how to do it...

What do you think?  Whatever we decide will be added to the guidelines.

### Why is this needed?

Well, it may not be needed, but it has certainly been a problem with GitHub repos in the past.

### What should happen?

Let's see.  The user here is the person who publishes the page and then has to do cleanup in GitHub.  

So, unless we can get GitHub to block indexing, this would mean extra work for the poster, once the item has been published elsewhere.

**Comment by jezdez** [comment]
I think it would be useful to move documents from the workspace into folders that match the category of the post, e.g. if we have a release announcement it would move from `workspace` to `news` or something?

I wonder if `drafts` would be a better title for `workspace` until the drafts are reviewed?

I could even image driving the publication from this repo automatically, it's not hard to build a GitHub Action Workflow that automatically publishes to Discourse when a file is added to a directory, e.g. `news` and opens a new pull request in the conda-dot-org website as well.
