### ISSUE TITLE
Create steering council mailing list

### ISSUE THREAD

**Issue by jezdez** [conda/communications#8]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

To easier reach the conda steering council, I think it would be great to have a steering AT lists.conda.org mailing list.

### Why is this needed?

We only have partial coverage for steering council members on the new Matrix platform, and it would be good to be able to reach them easily via email if needed.

**Comment by beckermr** [comment]
Shall we use a google list for this? Seems easiest.

**Comment by tnabtaf** [comment]
We could use a Google list.  That requires every member to have a Google account, which may not be acceptable.  It's not hard to setup a small list like this, and the annual expenditure is only around $10.

**Comment by beckermr** [comment]
I always prefer free over $$$.

**Comment by beckermr** [comment]
I have a google group I can direct add people to if we'd like.

**Comment by beckermr** [comment]
Invites are good too.

**Comment by jezdez** [comment]
I'd rather we stay with Sympa, to simplify the maintenance and have consistency with the announcement mailing list. I know it costs some money, but it's worth the cost compared to what Google Groups adds in maintenance burden, having to have a Google account and generally not being a user-friendly service.

**Comment by beckermr** [comment]
Fine by me!

**Comment by tnabtaf** [comment]
I will set it up. Give me a day or two.

**Comment by tnabtaf** [comment]
... or 3 days.

The steering council now [has a mailing list](https://lists.conda.org/wws/info/steering).  Some important bits

* Every current member of the steering council is now a member of the list
* New members have to be invited by an admin to join the list.
* Non-members can post, but are moderated.
* Archives are only readable to list members
* @tnabtaf and @jaimergp are currently list admins/moderators
  * We might want to drop @tnabtaf as a list moderator.  As a moderator he will be able to see moderated posts, even though he is not a list member. (He will still be able to do list configuration.)
  * Any volunteers to become a 2nd (or 3rd) list admin/moderator?  

I will leave this issue open for at least a few more days until things settle.  Please post here if you see issues.

**Comment by jakirkham** [comment]
Thanks @tnabtaf! 🙏

Is there a way to add other emails? Would like to add my NVIDIA email :)

**Comment by tnabtaf** [comment]
@jakirkham It's currently locked down so that only list admins can add emails.  But, we can add second emails for people too (although we need to pay a little more if and when we go over 25 email addresses).

And I have your NVIDIA email.  I will add it now.

**Comment by tnabtaf** [comment]
@beckermr pointed out that list membership should be offered to Emeritus members as well.  So I have.  One confirmation so far.

**Comment by tnabtaf** [comment]
Hi All, mailing list created, all current members subscribed, and all emeritus members have been invited (and some have been subscribed too).

Closing this issue.
