### ISSUE TITLE
Create new Matrix channel for installer team

### ISSUE THREAD

**Issue by jezdez** [conda/communications#9]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

For the [newly created incubator installer team](https://github.com/conda-incubator/installer/pull/1), we need a dedicated public place for conversations.

Could we please have a new Matrix channel with me and a few key members as admins (e.g. @jaimergp, @xhochy, @pseudoyim)?

**Comment by tnabtaf** [comment]
@jezdez Since there were no down votes, [this channel has been created](https://app.element.io/#/room/#conda-installer:matrix.org).  I will close this issue, and I'll make you a room admin, once you join.
